version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  db:
    build: db/.
    restart: always
    environment:
      MySQL_Root_Password: example
      MySQL_DATABASE: employees
      MSQL_ROOT_HOST: '%'
    ports:
      - "33060:3306"